# Neural Network from scratch

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Single neuron

- Each Neuron has a input, weight and biases
- Weight and bias changes during training
- The value of weight and biases are what get trained, and they are what make a model work or not work.

In [2]:
# Example of neuron that has a weights and bias
'''
This single neuron has a three inputs, 
- One neuron has only one bias
'''
inputs = [5, 7, 9]
weights = [0.4, 0.7, -0.3]
bias = 2.3

# Output of this neuron
'''
Neuron calculation
-> output = input*weights + bias
'''
output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] + bias)
print(output)

6.499999999999999


In [3]:
# Ex: Neuron with four inputs
# ---
# Neuron inputs
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
# Neuron outputs
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

print(output)


4.8


## A Layer of Neurons

- In NN typically have layers that consist of more than one neuron. Layers are nothing more than groups of neurons
- Neuron input can be trained data or output from previous neuron

In [4]:
# Eg: layes that has 3 neuron and 4 inputs
#---
# inputs
inputs = [1, 2, 3, 2.5]

# weigths
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

# bias
bias1 = 2
bias2 = 3
bias3 = 0.5

# layers of neurons
layer = [
    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,
    
    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,
    
    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3
]

print(layer)



[4.8, 1.21, 2.385]


## Upgrading current method of calculating nn

In [7]:
# Previous exemple with upgraded method
# initial inputs, weight and biases
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Output layers
layer = []

# Iterare for each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Output of given neuron
    neuron_output = 0
    # calulating for each input and weight
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron output variable
        neuron_output += n_input*weight
    # Add bias to neuron
    neuron_output += neuron_bias
    # Put neuron output to layer
    layer.append(neuron_output)

print(layer)



[4.8, 1.21, 2.385]


## Tensor, Arrays and Vectors

- A Tensor object is an object that can be represented as an array
- Vector can be call a list in Python and Array others
- Matrics can be call list of list on Python

In [8]:
tensor = [[[2, 4, 9],
          [5, 3, 5]],
         [[5, 8, 1],
          [4, 7,9.2]]]

vector = [2, 4, 1, 4] # array

matrics = [[3, 2],
          [4, 1],
          [2, 1]]

print(tensor,"\n",vector,"\n", matrics)

[[[2, 4, 9], [5, 3, 5]], [[5, 8, 1], [4, 7, 9.2]]] 
 [2, 4, 1, 4] 
 [[3, 2], [4, 1], [2, 1]]


## Dot Product and Vector Addition
- A dot product of two vectors is a sum of product of consecutive vector elements
- Both vectors must be of the same size

In [9]:
a = [1, 2, 3]
b = [2, 3, 4]
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
dot_product

20

## Single Neuron with Numpy

In [10]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = np.dot(weights, inputs) + bias
output

4.8

## A Layer of Neurons with NumPy


In [11]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases

layer_outputs

array([4.8  , 1.21 , 2.385])

In [12]:
inputs = np.array([1.0, 2.0, 3.0, 2.5])
weights = np.array([[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]])
biases = np.array([2.0, 3.0, 0.5])
inputs, weights, biases

(array([1. , 2. , 3. , 2.5]),
 array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
        [ 0.5 , -0.91,  0.26, -0.5 ],
        [-0.26, -0.27,  0.17,  0.87]]),
 array([2. , 3. , 0.5]))

In [13]:
mat1 = [[1, 2, 4],
       [2, 4, 5]]
mat2 = [2, 4, 6]
np.dot(mat1, mat2)

array([34, 50])

**NOTE**: When it comes to dot product 
```
    array[2, 4, 7] 
    
    array[[2],                                                    
          [4], 
          [7]] 
 ```
 Are same

## A Batch of Data 

- A Batch is a sample of data that given as a inputs at a time

In [14]:
batch = [[2, 4, 2],
        [3, 5, 1],
        [5, 8, 9],
        [1, 2, 4]]

## Matrix Product

In [15]:
mat1 = [[2, 4, 5],
       [4, 5, 1],
       [6, 7, 3]]
mat2 = [[3, 9, 6],
       [1, 5, 0],
       [4, 5, 1]]
np.dot(mat1, mat2)

array([[ 30,  63,  17],
       [ 21,  66,  25],
       [ 37, 104,  39]])

## Transposition of the matrix product

In [16]:
mat = np.array([
       [1, 3, 2],
       [3, 1, 5],
       [5, 8, 1]
      ])
print(mat, "\n")
print(np.transpose(mat))

[[1 3 2]
 [3 1 5]
 [5 8 1]] 

[[1 3 5]
 [3 1 8]
 [2 5 1]]


In [17]:
# array expense
a = np.array([[1, 2, 3], [4, 2, 9]])
a2 = np.array([a])
a3 = np.expand_dims(np.array(a), axis=1)
print(a)
print("------------------")
print(a2, a2.ndim, a.ndim)
print("------------------")
print(a3, a3.ndim, a.ndim)

[[1 2 3]
 [4 2 9]]
------------------
[[[1 2 3]
  [4 2 9]]] 3 2
------------------
[[[1 2 3]]

 [[4 2 9]]] 3 2


In [18]:
mat = np.array([[2, 1, 4], [5, 1, 7], [6, 2, 3]])
print(mat, mat.ndim)
print("------------")
print(np.expand_dims(mat, axis=1), np.expand_dims(mat, axis=1).ndim)

[[2 1 4]
 [5 1 7]
 [6 2 3]] 2
------------
[[[2 1 4]]

 [[5 1 7]]

 [[6 2 3]]] 3


In [19]:
# transpose
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T
print(a)
print(b)
print(np.dot(b, a), a.ndim, b.ndim)

[[1 2 3]]
[[2]
 [3]
 [4]]
[[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]] 2 2


## A Layer of Neurons & Batch of Data with NumPy

In [20]:
inputs = [[1.0, 2.0, 3.0, 2.5],
         [2.0, 5.0, -1.0, 2.0],
         [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases

print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


## Adding Layers

- Neural network with two layers

In [21]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
         [2., 5., -1., 2.],
         [-1.5, 2.7, 3.3, -0.8]]
# Layer 1: weights & biases
weights = [[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Layer 2: weights & biases
weights2 = [[0.1, -0.14, 0.5],
          [-0.5, 0.12, -0.33],
          [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Layer 1: Calculation
layer1 = np.dot(inputs, np.array(weights).T) + biases

# Layer 2: Calculation
layer2 = np.dot(layer1, np.array(weights2).T) + biases2

print("Layer 1: output\n",layer1)
print("Layer 2: output\n",layer2)


Layer 1: output
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
Layer 2: output
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
