# Neural Network from scratch

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Single neuron

- Each Neuron has a input, weight and biases
- Weight and bias changes during training
- The value of weight and biases are what get trained, and they are what make a model work or not work.

In [2]:
# Example of neuron that has a weights and bias
'''
This single neuron has a three inputs, 
- One neuron has only one bias
'''
inputs = [5, 7, 9]
weights = [0.4, 0.7, -0.3]
bias = 2.3

# Output of this neuron
'''
Neuron calculation
-> output = input*weights + bias
'''
output = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] + bias)
print(output)

6.499999999999999


In [3]:
# Ex: Neuron with four inputs
# ---
# Neuron inputs
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
# Neuron outputs
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

print(output)


4.8


## A Layer of Neurons

- In NN typically have layers that consist of more than one neuron. Layers are nothing more than groups of neurons
- Neuron input can be trained data or output from previous neuron

In [4]:
# Eg: layes that has 3 neuron and 4 inputs
#---
# inputs
inputs = [1, 2, 3, 2.5]

# weigths
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

# bias
bias1 = 2
bias2 = 3
bias3 = 0.5

# layers of neurons
layer = [
    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,
    
    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,
    
    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3
]

print(layer)



[4.8, 1.21, 2.385]


## Upgrading current method of calculating nn

In [5]:
# Previous exemple with upgraded method
# initial inputs, weight and biases
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Output layers
layer = []

# Iterare for each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Output of given neuron
    neuron_output = 0
    # calulating for each input and weight
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron output variable
        neuron_output += n_input*weight
    # Add bias to neuron
    neuron_output += neuron_bias
    # Put neuron output to layer
    layer.append(neuron_output)

print(layer)



[4.8, 1.21, 2.385]


## Tensor, Arrays and Vectors

- A Tensor object is an object that can be represented as an array
- Vector can be call a list in Python and Array others
- Matrics can be call list of list on Python

In [6]:
tensor = [[[2, 4, 9],
          [5, 3, 5]],
         [[5, 8, 1],
          [4, 7,9.2]]]

vector = [2, 4, 1, 4] # array

matrics = [[3, 2],
          [4, 1],
          [2, 1]]

print(tensor,"\n",vector,"\n", matrics)

[[[2, 4, 9], [5, 3, 5]], [[5, 8, 1], [4, 7, 9.2]]] 
 [2, 4, 1, 4] 
 [[3, 2], [4, 1], [2, 1]]


## Dot Product and Vector Addition
- A dot product of two vectors is a sum of product of consecutive vector elements
- Both vectors must be of the same size

In [7]:
a = [1, 2, 3]
b = [2, 3, 4]
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
dot_product

20

## Single Neuron with Numpy

In [8]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = np.dot(weights, inputs) + bias
output

4.8

## A Layer of Neurons with NumPy


In [9]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases

layer_outputs

array([4.8  , 1.21 , 2.385])

In [10]:
inputs = np.array([1.0, 2.0, 3.0, 2.5])
weights = np.array([[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]])
biases = np.array([2.0, 3.0, 0.5])
inputs, weights, biases

(array([1. , 2. , 3. , 2.5]),
 array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
        [ 0.5 , -0.91,  0.26, -0.5 ],
        [-0.26, -0.27,  0.17,  0.87]]),
 array([2. , 3. , 0.5]))

In [11]:
mat1 = [[1, 2, 4],
       [2, 4, 5]]
mat2 = [2, 4, 6]
np.dot(mat1, mat2)

array([34, 50])

**NOTE**: When it comes to dot product 
```
    array[2, 4, 7] 
    
    array[[2],                                                    
          [4], 
          [7]] 
 ```
 Are same

## A Batch of Data 

- A Batch is a sample of data that given as a inputs at a time

In [12]:
batch = [[2, 4, 2],
        [3, 5, 1],
        [5, 8, 9],
        [1, 2, 4]]

## Matrix Product

In [13]:
mat1 = [[2, 4, 5],
       [4, 5, 1],
       [6, 7, 3]]
mat2 = [[3, 9, 6],
       [1, 5, 0],
       [4, 5, 1]]
np.dot(mat1, mat2)

array([[ 30,  63,  17],
       [ 21,  66,  25],
       [ 37, 104,  39]])

## Transposition of the matrix product

In [14]:
mat = np.array([
       [1, 3, 2],
       [3, 1, 5],
       [5, 8, 1]
      ])
print(mat, "\n")
print(np.transpose(mat))

[[1 3 2]
 [3 1 5]
 [5 8 1]] 

[[1 3 5]
 [3 1 8]
 [2 5 1]]


In [15]:
# array expense
a = np.array([[1, 2, 3], [4, 2, 9]])
a2 = np.array([a])
a3 = np.expand_dims(np.array(a), axis=1)
print(a)
print("------------------")
print(a2, a2.ndim, a.ndim)
print("------------------")
print(a3, a3.ndim, a.ndim)

[[1 2 3]
 [4 2 9]]
------------------
[[[1 2 3]
  [4 2 9]]] 3 2
------------------
[[[1 2 3]]

 [[4 2 9]]] 3 2


In [16]:
mat = np.array([[2, 1, 4], [5, 1, 7], [6, 2, 3]])
print(mat, mat.ndim)
print("------------")
print(np.expand_dims(mat, axis=1), np.expand_dims(mat, axis=1).ndim)

[[2 1 4]
 [5 1 7]
 [6 2 3]] 2
------------
[[[2 1 4]]

 [[5 1 7]]

 [[6 2 3]]] 3


In [17]:
# transpose
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T
print(a)
print(b)
print(np.dot(b, a), a.ndim, b.ndim)

[[1 2 3]]
[[2]
 [3]
 [4]]
[[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]] 2 2


## A Layer of Neurons & Batch of Data with NumPy

In [18]:
inputs = [[1.0, 2.0, 3.0, 2.5],
         [2.0, 5.0, -1.0, 2.0],
         [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases

print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


## Adding Layers

- Neural network with two layers

In [19]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
         [2., 5., -1., 2.],
         [-1.5, 2.7, 3.3, -0.8]]
# Layer 1: weights & biases
weights = [[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Layer 2: weights & biases
weights2 = [[0.1, -0.14, 0.5],
          [-0.5, 0.12, -0.33],
          [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Layer 1: Calculation
layer1 = np.dot(inputs, np.array(weights).T) + biases

# Layer 2: Calculation
layer2 = np.dot(layer1, np.array(weights2).T) + biases2

print("Layer 1: output\n",layer1)
print("Layer 2: output\n",layer2)


Layer 1: output
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
Layer 2: output
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


## Training Data

In [21]:
import numpy as np
import sklearn

import pandas as pd


df = pd.read_csv("../data/heart-disease.csv")

df.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [26]:
df.size

4242

In [90]:
features = df.drop("target", axis=1).to_numpy()

target = df["target"].to_numpy()
features, target, features.ndim

(array([[63.,  1.,  3., ...,  0.,  0.,  1.],
        [37.,  1.,  2., ...,  0.,  0.,  2.],
        [41.,  0.,  1., ...,  2.,  0.,  2.],
        ...,
        [68.,  1.,  0., ...,  1.,  2.,  3.],
        [57.,  1.,  0., ...,  1.,  1.,  3.],
        [57.,  0.,  1., ...,  1.,  1.,  2.]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [91]:
features = features[:15]
target = target[:15]
features, len(features), target, target.size

(array([[6.30e+01, 1.00e+00, 3.00e+00, 1.45e+02, 2.33e+02, 1.00e+00,
         0.00e+00, 1.50e+02, 0.00e+00, 2.30e+00, 0.00e+00, 0.00e+00,
         1.00e+00],
        [3.70e+01, 1.00e+00, 2.00e+00, 1.30e+02, 2.50e+02, 0.00e+00,
         1.00e+00, 1.87e+02, 0.00e+00, 3.50e+00, 0.00e+00, 0.00e+00,
         2.00e+00],
        [4.10e+01, 0.00e+00, 1.00e+00, 1.30e+02, 2.04e+02, 0.00e+00,
         0.00e+00, 1.72e+02, 0.00e+00, 1.40e+00, 2.00e+00, 0.00e+00,
         2.00e+00],
        [5.60e+01, 1.00e+00, 1.00e+00, 1.20e+02, 2.36e+02, 0.00e+00,
         1.00e+00, 1.78e+02, 0.00e+00, 8.00e-01, 2.00e+00, 0.00e+00,
         2.00e+00],
        [5.70e+01, 0.00e+00, 0.00e+00, 1.20e+02, 3.54e+02, 0.00e+00,
         1.00e+00, 1.63e+02, 1.00e+00, 6.00e-01, 2.00e+00, 0.00e+00,
         2.00e+00],
        [5.70e+01, 1.00e+00, 0.00e+00, 1.40e+02, 1.92e+02, 0.00e+00,
         1.00e+00, 1.48e+02, 0.00e+00, 4.00e-01, 1.00e+00, 0.00e+00,
         1.00e+00],
        [5.60e+01, 0.00e+00, 1.00e+00, 1.40e+02, 2.9

## Dense Layer Class

- reuseable dense layer class

In [92]:
class Dense_Layer:
    
    def __init__(self, n_inputs, n_neurons):
        # initialize weights and biases
        # random weights and biases initialization (Note: we can some use rules to initialize)  
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases
        



## Creating Dense Layer

In [93]:
# Create First desne layer: 
dense1 = Dense_Layer(13, 5)

# Forward pass
dense1.forward(features)

print(dense1.output)

[[-1.7324994  -1.19714928  4.84659565 -1.62733325 -1.71916107]
 [-1.03074887 -1.41346654  4.67012527 -1.29478684 -2.30465717]
 [-0.69102979 -1.2300923   4.17319853 -1.24792792 -2.02964   ]
 [-1.43135324 -1.30680445  4.56936351 -1.1356696  -1.74354371]
 [-3.3861265  -1.45038866  5.88727312 -1.47795393 -1.95449583]
 [-1.12995789 -1.12003054  4.22416125 -1.42460242 -1.64712902]
 [-2.51156072 -1.30623402  5.40504391 -1.6577584  -1.98061307]
 [-1.67156293 -1.33330639  4.76746793 -1.22788533 -2.02163409]
 [-0.74018664 -1.2218841   4.63230659 -1.84428056 -2.18247194]
 [-0.33255104 -1.21033183  4.10710184 -1.43154857 -1.8495672 ]
 [-1.57602444 -1.25734169  4.74714878 -1.493292   -1.890035  ]
 [-2.35925007 -1.2157865   5.01623727 -1.60908115 -1.92606821]
 [-1.79067311 -1.34428052  4.93926593 -1.38505135 -2.02673552]
 [-1.68819838 -1.10725264  4.24206892 -1.16777661 -1.25866664]
 [-2.21081083 -1.32919387  5.44731664 -1.76770561 -2.07939268]]


## Activation Function

### The Step Activation Function

The purpose of this function serves is to mimic a neuron "firing" or "not firing" based on input information.

In a single neuron, if the weight.inputs + bias results in a value greater than 0, the neuron will fire and output a 0; otherwise, it will output a 0.

This activation function has been used historically in hidden layers, but nowadays, it is rarely a choice.

```
y = {
      0 if x <= 0
      1 if x >  0
    }
```

### The Linear Activation Function

A Linear function is simply the equation of a line. it will appear as a straight line when graphed, where `y=x` and the output value equals the input.<br />

This activation  function is usually applied to the last layer's output in the case of a regression modal.


### The Sigmoid Activation Function

```
y = 1/(1+e^-x)
```
This activation function is more granular for neural network. <br />

This function returns a value in the range of 0 for negative infinity, through 0.5 for the input of 0, and to 1 for positive infinity.<br />

The **Sigmoid** function is replaced by **ReLU** function

### The Rectified Linear Activation Function

```
y = {
    x x >  0
    0 x <= 0
}
```
The **ReLU** finction is simpler than the sigmoid. It's quite literally `y=x`.<br />

If `x` is less than or equal to 0, then `y` is 0 otherwise, `y` is equal to `x`. <br />

This function simple but most widely used activation function. <br />

The ReLU Activation function is extremely close to being a linear activation function while remaining nonlinear, due to that bend after 0.


### Linear Activation in the Hidden Layers

If we use linear function in a neural network, No matter what we do, with the neuron's weights and biases, the output of this neuron will be perfectly linear to `y=x` of the activation function. This linear nature will continue throughout the network:

In [ ]:
# Layer with linear activation function
